apiVersion: v1
kind: Pod
metadata:
  name: adapter
  namespace: default
spec:
  containers:
  - name: redis-service
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  # Provide an adatper that implements the Promethus interface
  - name: adapter
    image: oliver006/redis_exporter
    
